import Head from 'next/head';
import axios from 'axios';
import Navbar from '../../components/header/navbar';

export async function getStaticPaths() {
  const res = await axios.get('http://localhost:1337/api/accommodations');
  const result = res.data;
  const id = result?.data;

  const paths = id.map((accommodations) => ({
    params: { id: accommodations.id.toString() },
  }));

  return { paths, fallback: false };
}

export async function getStaticProps({ params }) {
  const res = await axios.get(
    `http://localhost:1337/api/accommodations/${params.id}`
  );
  const accommodations = res?.data.data;
  return { props: { accommodations } };
}

const Accommodations = ({ accommodations }) => {
  return (
    <div className='bg-bgColor'>
      <Head>
        <title>Holidaze</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className='sticky top-0 z-50'>
        <Navbar />
      </header>
      <main className='mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28'>
        <h1>{accommodations.attributes.name}</h1>
      </main>
    </div>
  );
};

export default Accommodations;
