import Head from 'next/head';
import { useState } from 'react';
import axios from 'axios';
import Image from 'next/image';
import Navbar from '../../components/header/navbar';
import FooterSection from '../../components/footer/footer';
import TypeLabel from '../../components/labels/typeLabel';
import BookButton from '../../components/buttons/bookButton';
import LocationLabel from '../../components/labels/locationLabel';
import Reviews from '../../components/reviews/reviews';

import styles from '../../styles/Home.module.css';

export async function getStaticPaths() {
  const res = await axios.get(
    'http://localhost:1337/api/accommodations?populate=*'
  );
  const result = res.data;
  const id = result?.data;

  const paths = id.map((accommodations) => ({
    params: { id: accommodations.id.toString() },
  }));

  return { paths, fallback: false };
}

export async function getStaticProps({ params }) {
  const res = await axios.get(
    `http://localhost:1337/api/accommodations/${params.id}?populate=*`
  );
  const accommodations = res?.data.data;
  return { props: { accommodations } };
}

const Accommodations = ({ accommodations, labelType }) => {
  const [showMore, setShowMore] = useState();
  return (
    <div className='bg-bgColor'>
      <Head>
        <title>Holidaze</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className='sticky top-0 z-50'>
        <Navbar />
      </header>
      <main className='mt-4 mx-auto max-w-7xl px-4 sm:mt-2 sm:px-6 md:mt-5 lg:mt-10 lg:px-8 xl:mt-10'>
        <div className={styles.accommodationsImg}>
          <Image
            className={styles.accommodationsImg}
            src={accommodations.attributes.card_image}
            layout='fill'
            objectFit='cover'
            alt={accommodations.attributes.name}
          ></Image>
        </div>
        <div className='mt-4'>
          <TypeLabel
            type={accommodations.attributes.categories.data[0].attributes.name}
          ></TypeLabel>
        </div>
        <div className='mt-4 flex justify-between items-center'>
          <h1 className='text-3xl font-serif2 font-bold'>
            {accommodations.attributes.name}
          </h1>
          <div className='flex items-center'>
            <p className='mr-4 text-blue-5 text-lg font-bold'>
              ${accommodations.attributes.price}
              <span className='text-black opacity-50 font-medium'>
                {' '}
                /per night
              </span>{' '}
            </p>
            <BookButton />
          </div>
        </div>
        <div>
          <LocationLabel location={accommodations.attributes.location} />
        </div>
        <div className='mt-4 w-1/2'>
          <p className='font-serif'>
            {showMore
              ? accommodations.attributes.description
              : `${accommodations.attributes.description.substring(0, 390)}`}
            <button
              onClick={() => setShowMore(!showMore)}
              className='text-blue-5'
            >
              {showMore ? 'Show less' : '... Show more'}
            </button>
          </p>
        </div>
        <div className='mt-4 mb-10'>
          <Reviews />
        </div>
      </main>
      <footer className='bg-footerColor'>
        <FooterSection />
      </footer>
    </div>
  );
};

export default Accommodations;
