import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Navbar from '../components/header/navbar';
import Hero from '../components/main/hero';

export default function Home() {
  return (
    <div className='bg-bgColor'>
      <Head>
        <title>Holidaze</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>
        <Navbar />
      </header>

      <main className='mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28'>
        <Hero />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
