import Head from 'next/head';
import Navbar from '../components/header/navbar';
import FooterSection from '../components/footer/footer';
import SearchInput from '../components/search/searchInput';
import SearchButton from '../components/buttons/searchButton';
import FilterButton from '../components/buttons/filterButton';
import Types from '../components/search/types';
import SearchResults from '../components/search/searchResults';

export default function Search() {
  return (
    <div className='bg-bgColor'>
      <Head>
        <title>Holidaze</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>
        <Navbar />
      </header>
      <main className='mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28'>
        <div className='flex justify-between w-full'>
          <div className='flex w-4/5'>
            <SearchInput />
            <SearchButton />
          </div>
          <div>
            <FilterButton />
          </div>
        </div>
        <h2 className='font-extrabold font-serif2 text-black text-xl mt-5'>
          Types
        </h2>
        <div className='flex w-1/4 mt-5'>
          <Types />
        </div>
        <section className='mt-10 mb-10'>
          <h2 className='font-extrabold font-serif2 text-black text-2xl mt-5'>
            Results
          </h2>
          <div className='w-full mt-5'>
            <SearchResults />
          </div>
        </section>
      </main>
      <footer className='bg-footerColor'>
        <FooterSection />
      </footer>
    </div>
  );
}
